import Foundation
import UniformTypeIdentifiers
import CoreTransferable

/// Where a canvas node's content originated.
enum NodeSource: Equatable {
    /// User-created note.
    case manual
    /// Imported from a chat message.
    case chat(ChatOrigin)
    /// Generated by AI from other nodes.
    case ai(AIOrigin)

    struct ChatOrigin: Equatable {
        let chatId: String
        let chatTitle: String
        let role: MessageRole
        let agentCategory: AgentCategory?
        let timestamp: Date
    }

    struct AIOrigin: Equatable {
        let action: String        // "summarize", "expand", "connect", or custom prompt
        let sourceNodeIds: [UUID]
        let timestamp: Date
    }
}

/// A single element on the infinite canvas.
struct CanvasNode: Identifiable, Equatable {
    let id: UUID
    var position: CGPoint
    var text: String
    var width: CGFloat
    var color: NodeColor
    var source: NodeSource
    var groupId: UUID?

    init(
        id: UUID = UUID(),
        position: CGPoint,
        text: String = "",
        width: CGFloat = 200,
        color: NodeColor = .note,
        source: NodeSource = .manual,
        groupId: UUID? = nil
    ) {
        self.id = id
        self.position = position
        self.text = text
        self.width = width
        self.color = color
        self.source = source
        self.groupId = groupId
    }

    var isChatNode: Bool {
        if case .chat = source { return true }
        return false
    }

    var isAINode: Bool {
        if case .ai = source { return true }
        return false
    }

    enum NodeColor: String, CaseIterable {
        case note, idea, task, reference, ai

        var hue: Double {
            switch self {
            case .note:      return 0.0        // neutral
            case .idea:      return 0.13        // amber
            case .task:      return 0.58        // cyan
            case .reference: return 0.75        // purple
            case .ai:        return 0.35        // green-teal
            }
        }
    }
}

/// A directional connection between two canvas nodes.
struct CanvasEdge: Identifiable, Equatable {
    let id: UUID
    var fromId: UUID
    var toId: UUID
    var label: String?

    init(id: UUID = UUID(), fromId: UUID, toId: UUID, label: String? = nil) {
        self.id = id
        self.fromId = fromId
        self.toId = toId
        self.label = label
    }
}

/// A visual group/frame containing nodes on the canvas.
struct CanvasGroup: Identifiable, Equatable {
    let id: UUID
    var title: String
    var position: CGPoint       // top-left corner in canvas space
    var size: CGSize
    var color: CanvasNode.NodeColor
    var isCollapsed: Bool

    init(
        id: UUID = UUID(),
        title: String = "Group",
        position: CGPoint,
        size: CGSize = CGSize(width: 400, height: 300),
        color: CanvasNode.NodeColor = .note,
        isCollapsed: Bool = false
    ) {
        self.id = id
        self.title = title
        self.position = position
        self.size = size
        self.color = color
        self.isCollapsed = isCollapsed
    }
}

// MARK: - Drag & Drop

/// Lightweight payload for dragging a chat from the sidebar onto the canvas.
struct ChatDragItem: Codable, Transferable {
    let chatId: String
    let chatTitle: String

    static var transferRepresentation: some TransferRepresentation {
        CodableRepresentation(contentType: .macbotChat)
    }
}

extension UTType {
    static let macbotChat = UTType(exportedAs: "com.macbot.chat-drag")
}
